name: Run Recipes API Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-recipes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and run containers
        run: |
          docker compose up -d --build

      - name: Wait for API to be ready
        run: |
          echo "Waiting for Flask API..."
          for i in {1..20}; do
            if curl -s http://localhost:5000/recipes > /dev/null; then
              echo "API is ready"
              break
            fi
            echo "Waiting 3s..."
            sleep 3
          done

      - name: Run API tests
        run: |
          pip install requests
          BASE_URL=http://localhost:5000 python3 tests/recipes-test.py

      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        if: success()
        run: |
          docker tag flask-app-1 ${{ secrets.DOCKERHUB_USERNAME }}/recipes_flask:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/recipes_flask:latest

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "GitHub Actions â€“ Recipes API Test Failed"
          body: "The CI test failed. Please check the GitHub Actions logs."
          to: ntimsit@g.jct.ac.il
          from: GitHub Actions

      - name: Stop containers
        if: always()
        run: docker compose down
